replicaCount: 3
image:
  repository: crypticseeds/yelp-camp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

probes:
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30

doppler:
  serviceToken: "" # Empty default, will be overridden by doppler-values.yaml
