apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "yelp-camp.fullname" . }}-certbot
  labels:
    {{- include "yelp-camp.labels" . | nindent 4 }}
    app.kubernetes.io/component: certbot
spec:
  template:
    metadata:
      labels:
        {{- include "yelp-camp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: certbot
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: certbot-config
          emptyDir: {}
        - name: certbot-work
          emptyDir: {}
      containers:
        - name: certbot
          image: "{{ .Values.certbot.image.repository }}:{{ .Values.certbot.image.tag }}"
          args:
            - certonly
            - --webroot
            - -w
            - /var/www/certbot
            - -d
            - {{ .Values.domain }}
            - --email
            - {{ .Values.certbot.email }}
            - --agree-tos
            - --no-eff-email
            - --force-renewal
            - --dry-run
          volumeMounts:
            - name: certbot-config
              mountPath: /etc/letsencrypt
            - name: certbot-work
              mountPath: /var/www/certbot