apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "yelp-camp.fullname" . }}-certbot-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "yelp-camp.labels" . | nindent 4 }}
    app.kubernetes.io/component: certbot
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "yelp-camp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: certbot
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: certbot-config
          emptyDir: {}
        - name: certbot-work
          emptyDir: {}
      containers:
        - name: certbot
          image: "{{ .Values.certbot.image.repository }}:{{ .Values.certbot.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              certbot certonly --webroot \
                -w /var/www/certbot \
                -d {{ .Values.domain }} \
                --email {{ .Values.certbot.email }} \
                --agree-tos \
                --no-eff-email \
                --force-renewal \
                --rsa-key-size 4096 \
                --verbose \
                --keep-until-expiring \
                --expand
          volumeMounts:
            - name: certbot-config
              mountPath: /etc/letsencrypt
            - name: certbot-work
              mountPath: /var/www/certbot