apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret
  labels:
    {{- include "yelp-camp.labels" . | nindent 4 }}
type: Opaque
data:
  serviceToken: {{ .Values.doppler.serviceToken | b64enc }}
