apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ include "yelp-camp.fullname" . }}-doppler
spec:
  tokenSecret:
    name: doppler-token-secret # This should be created separately with your Doppler service token
  managedSecret:
    name: {{ include "yelp-camp.fullname" . }}-secrets
    keys:
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_KEY
      - CLOUDINARY_SECRET
      - MAPBOX_TOKEN
      - DB_URL
      - SECRET
