apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yelp-camp.fullname" . }}-nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      access_log /var/log/nginx/access.log;

      server {
        listen 80;
        server_name localhost;

        location / {
          return 200 'Nginx is running!';
        }
      }
    }