apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yelp-camp.fullname" . }}-nginx
  labels:
    {{- include "yelp-camp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "yelp-camp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "yelp-camp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "yelp-camp.fullname" . }}-nginx-config
        - name: certbot-webroot
          emptyDir: {}
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: certbot-webroot
              mountPath: /var/www/certbot
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20