apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yelp-camp.fullname" . }}-nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        server_name {{ .Values.domain }};
        
        location / {
          proxy_pass http://{{ include "yelp-camp.fullname" . }}:{{ .Values.service.port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /.well-known/acme-challenge/ {
          root /var/www/certbot;
        }
      }
      
      # Commented out SSL configuration until certificates are available
      # server {
      #   listen 443 ssl;
      #   server_name {{ .Values.domain }};
      #   
      #   ssl_certificate /etc/letsencrypt/live/{{ .Values.domain }}/fullchain.pem;
      #   ssl_certificate_key /etc/letsencrypt/live/{{ .Values.domain }}/privkey.pem;
      #   
      #   location / {
      #     proxy_pass http://{{ include "yelp-camp.fullname" . }}:{{ .Values.service.port }};
      #     proxy_set_header Host $host;
      #     proxy_set_header X-Real-IP $remote_addr;
      #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #     proxy_set_header X-Forwarded-Proto $scheme;
      #   }
      # }
    }